config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :articles #, path: 'cars'
  resources :users, except: [:new]

  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    has_secure_password
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}
    before_save {self.email = email.downcase}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform this action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = 'Article was successfully created'
      # redirect to a show action
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated'
      redirect_to article_path(@article)
    else
      flash[:success] = 'Article was not updated'
      render 'edit'
    end
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @article.destroy
    flash[:success] = 'Article was deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
    end

    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have logged in"
            redirect_to users_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the alpha bog #{@user.username}"
            redirect_to articles_path
        else
            render "new"
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was successfully updated"
            redirect_to articles_path
        else
            render "edit"
        end
    end

    def show
        @user = User.find(params[:id])
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<div class="row">
    <div class="col-sm-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description %>
            </div>
            <div class="col-sm-6">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: 'btn btn-primary btn-large' %>
            </div>
        </div>
        <% end %>
    </div>
</div>







app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center">Listing all articles</h1>
<%= render "shared/article", obj: @articles %>
<div>
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h2 class="text-center">Title: <%= @article.title %></h2>
<div class="card col-sm-4 col-sm-offset-2 text-center">
    <% if @article.user %>
    <ul class="listing">
        <div class="row text-center">
            <div class="col-sm-4 col-sm-offset-4">
                <li>
                    <%= link_to gravatar_for(@article.user, size: 150), user_path(@article.user) %>
                </li>
                <li class="article-title">
                    <%= link_to @article.user.username, user_path(@article.user) %>
                </li>
                <li>
                    <small>
                        <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                    </small>
                </li>
            </div>
        </div>
    </ul>
    <% end %>
    <h4 class="text-center description">
        <strong>Description: </strong>
    </h4>
    <hr>
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
        <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger" %>
        <%= link_to 'Back', articles_path, class: "btn btn-sm btn-success" %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Article", new_article_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign in", login_path, class: "nav-link" %>
        <% end %>
      </li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>
<%= link_to 'About', about_path %>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="card">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-meta-details">
                        <small>Created by: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
                <div class="article-actions">
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-primary" %>
                    <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-sm btn-danger" %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-sm-12 col-sm-offset-2">
            <div class="card bg-danger">
                <div class="card-header">
                    <h2 class="card-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited the article from being saved:
                    </h2>
                    <div class="card-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg|%>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-sm-10 col-sm-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
<div class="row">
    <div class="col-sm-8">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :email %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
        </div>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password %>
            </div>
            <div class="col-sm-6">
                <%= f.text_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-small') %>
            </div>
        </div>
        <% end %>

        <div class="col-sm-4 col-sm-offset-2">
        <%= link_to "Cancel request and return to articles listing", articles_path %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align = "center">Edit user account</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center">All users</h1>
<div class="text-center">
    <% @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="card col-sm-8 col-offset-2">
                    <li>
                        <%= link_to gravatar_for(user), user_path(user) %>
                    </li>
                    <li class="article-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li>
                        <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
                    </li>
                </div>
            <div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Signup</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
    <div class="col-sm-4 col-sm-offset-4 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>

<h4 class="text-center"><%= @user.username %>'s articles</h4>

<%= render "shared/article", obj: @user.articles %>

<div>
 <%= will_paginate @user_articles %>
</div>